server:
  port: 9060
spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: magic123
    hikari:
      connectionTimeout: 2000
      maximum-pool-size: 20
      poolName: my-pool
      maxLifetime: 1000000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 25
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update



  profiles:
    active: dev
  account:
    generator:
      enabled: false
  generator:
    limit: 300
    enabled: false



#logging:
#  level:
#    org:
#      hibernate:
#        SQL: INFO
#        type:
#          descriptor:
#            sql:
#              BasicBinder: INFO
#    com:
#      zaxxer:
#          hikari:
#            HikariConfig: INFO
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
management:
  server: localhost

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"